/*
 EPF 2A
 Auteurs : Nicolas Breton et Cecile Tran
 Zombie shooter
 Groupe A
 Date : 02/02/15
 Edit : 15/05/15
 */
package pfiches;

import CecileTran_projetcpo.Jeu;
import static CecileTran_projetcpo.Jeu.DOSS_IMAGES;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class FScores extends javax.swing.JDialog {

    final int COLONNES = 3;
    final int LIGNES = 11;
    private Jeu jeu;
    private Image img;
    private JLabel tabLabel[][];

    public FScores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(600, 500);
        initialiser();
        initFond();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layeredPane = new javax.swing.JLayeredPane();
        lScores = new javax.swing.JLabel();
        lFond = new javax.swing.JLabel();
        bRetour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bRetour.setBackground(new java.awt.Color(51, 153, 255));
        bRetour.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        bRetour.setForeground(new java.awt.Color(237, 244, 255));
        bRetour.setText("Retour");
        bRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layeredPaneLayout = new javax.swing.GroupLayout(layeredPane);
        layeredPane.setLayout(layeredPaneLayout);
        layeredPaneLayout.setHorizontalGroup(
            layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layeredPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lScores, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
            .addGroup(layeredPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lFond, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(527, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layeredPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bRetour)
                .addGap(30, 30, 30))
        );
        layeredPaneLayout.setVerticalGroup(
            layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layeredPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lFond, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(lScores, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layeredPane.setLayer(lScores, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPane.setLayer(lFond, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPane.setLayer(bRetour, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRetourActionPerformed

        this.setVisible(false);
        getParent().setVisible(true);
    }//GEN-LAST:event_bRetourActionPerformed

    public void initialiser() {
        tabLabel = new JLabel[LIGNES][COLONNES];

        GridLayout gest = new GridLayout(0, COLONNES);
        lScores.setLayout(gest);
        for (int i = 0; i < tabLabel.length; i++) {
            for (int j = 0; j < tabLabel[i].length; j++) {
                //creer un label
                JLabel lab = new JLabel();
                //définir la taille du label
                Dimension dim = new Dimension(60, 60);
                lab.setPreferredSize(dim);
                //ajouter le label dans le tableau
                tabLabel[i][j] = lab;
                //ajouter le label dans le panel
                lScores.add(tabLabel[i][j]);
                tabLabel[i][j].setHorizontalAlignment(JLabel.CENTER);
                tabLabel[i][j].setFont(new java.awt.Font("Verdana", 1, 14));
                tabLabel[i][j].setForeground(new java.awt.Color(255, 255, 255));
                tabLabel[i][j].setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
            }
        }
        this.pack(); //mettre a jour l'affichage
        jeu = new Jeu("Toto");

        tabLabel[0][0].setText("Rang");
        tabLabel[0][0].setFont(new java.awt.Font("Lucida Handwriting", 1, 18));
        tabLabel[0][1].setText("Nom Joueur");
        tabLabel[0][1].setFont(new java.awt.Font("Lucida Handwriting", 1, 18));
        tabLabel[0][2].setText("Score");
        tabLabel[0][2].setFont(new java.awt.Font("Lucida Handwriting", 1, 18));
        for (int d = 1; d < LIGNES; d++) {
            tabLabel[d][0].setText("" + d);
        }
        jeu.trierScore(tabLabel);

    }

    public void initFond() {
        //acces au toolkit
        Toolkit t = Toolkit.getDefaultToolkit();
        //acces a l'image
        img = t.getImage(DOSS_IMAGES + "FondScores.jpg");
        img = img.getScaledInstance(600, 500, Image.SCALE_DEFAULT);

        layeredPane.setPreferredSize(new Dimension(600, 500));

        this.setContentPane(layeredPane);

        layeredPane.add(lFond, 1);

        lFond.setIcon(new ImageIcon(img));
        lFond.setPreferredSize(new Dimension(600, 500));
        lFond.setBounds(0, 0, 600, 500);

        layeredPane.add(lScores, 0);
        layeredPane.add(bRetour, 0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FScores dialog = new FScores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRetour;
    private javax.swing.JLabel lFond;
    private javax.swing.JLabel lScores;
    private javax.swing.JLayeredPane layeredPane;
    // End of variables declaration//GEN-END:variables
}
